### ISSUE TITLE
Version prerequisites and updated docker-compose file to run this repo

### ISSUE THREAD

**Issue by KunalArora** [tuanavu/airflow-tutorial#52]
Following are the version prerequisites to run this repo, along with the updated docker-compose.yml file. 

docker version => 20.10.8, build 3967b7d
docker-compose version => 1.27.4, build unknown
airflow version => 2.1.3

Updated docker-compose.yml file:
```
version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    image: puckel/docker-airflow:1.10.9
    build:
      context: https://github.com/puckel/docker-airflow.git#1.10.9
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: gcp_api,s3
        PYTHON_DEPS: sqlalchemy==1.3.0
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
    volumes:
      - ./examples/intro-example/dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
```

**Comment by Aeroban** [comment]
Hello, I just want to add that it is also possible to run this repo without installing airflow on your local machine. As of 15 Nov 2021, I've run into incompatibilities with wtforms and pandas-gbq (for the BigQuery part). Thus, my solution is by adding it into the PYTHON_DEPS manually. Please keep in mind that I'm new to this and do not know how docker really works. May not be the best solution but it runs.

Docker Version -> 20.10.7 build f0df350
Docker Compose -> 1.29.2, build 5becea4c

Updated docker-compose-gcloud.yml

```
version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    image: puckel/docker-airflow:1.10.9
    build:
      context: https://github.com/puckel/docker-airflow.git#1.10.9
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: gcp_api,s3
        PYTHON_DEPS: sqlalchemy==1.3.0 wtforms==2.2.1 pandas-gbq==0.14.1        
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
    volumes:
      - ./examples/gcloud-example/dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
```

Thank you for the recommendation of using puckel/docker-airflow:1.10.9 and sqlalchemy==1.3.0. Cheers!
